name: Update Feed

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update feed date
        run: |
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          DATE_RFC=$(date -R)
          sed "s/{{DATE}}/$DATE/g; s/{{DATE_RFC}}/$DATE_RFC/g" feed_template.rss > feed.rss

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add feed.rss
          git commit -m "Auto update feed at $(date)" || echo "No changes to commit"
          git push
